# Generated by Django 4.0.2 on 2022-02-10 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produto_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
