# Generated by Django 4.0.2 on 2022-02-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_rename_preco_produto_preco_marketing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='imagem',
            new_name='imagem2',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem1',
            field=models.ImageField(default=1, upload_to='produto_imagem/%Y/%m'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem3',
            field=models.ImageField(blank=True, null=True, upload_to='produto_imagem/%Y/%m'),
        ),
    ]
