# Generated by Django 4.0.2 on 2022-02-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_rename_imagem_produto_imagem2_produto_imagem1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default=1, upload_to='produto_imagem/%Y/%m'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem1',
            field=models.ImageField(blank=True, null=True, upload_to='produto_imagem/%Y/%m'),
        ),
    ]
