# Generated by Django 4.0.2 on 2022-02-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_produto_imagem_alter_produto_imagem1'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem4',
            field=models.ImageField(blank=True, null=True, upload_to='produto_imagem/%Y/%m'),
        ),
    ]
