# Generated by Django 4.0.2 on 2022-02-15 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_produto_imagem4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem4',
        ),
    ]
