# Generated by Django 4.0.2 on 2022-02-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_remove_produto_imagem4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descricao_curta',
            new_name='descricao',
        ),
    ]
