# Generated by Django 4.0.2 on 2022-03-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_rename_descricao_curta_produto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_promocional',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Preço Promo.'),
        ),
    ]
